#!/bin/sh
# Assembles PDFReader.app from the SwiftPM build output and ad-hoc signs it.
#
# Why a bundle: on macOS Tahoe cursor changes (resize handle, I-beam, …)
# only render when running as a proper `.app`. A raw `swift run` binary
# runs fine otherwise, but the pointer stays an arrow everywhere.
#
# Usage:
#   scripts/make-app.sh [debug|release]   # default: debug
#   APP_BINARY=.build/universal/PDFReader scripts/make-app.sh release
#   open .build/app/PDFReader.app
#
# APP_BINARY packages a prebuilt binary instead of building (used by CI to
# embed a lipo-combined universal binary).
set -eu
cd "$(dirname "$0")/.."

CONFIG="${1:-debug}"
APP_DIR=".build/app/PDFReader.app"
if [ -n "${APP_BINARY:-}" ]; then
    BIN="$APP_BINARY"
else
    swift build -c "$CONFIG" --product PDFReader
    BIN=".build/debug/PDFReader"
    if [ "$CONFIG" = "release" ]; then
        BIN=".build/release/PDFReader"
    fi
fi

rm -rf "$APP_DIR"
mkdir -p "$APP_DIR/Contents/MacOS" "$APP_DIR/Contents/Resources"
cp "$BIN" "$APP_DIR/Contents/MacOS/PDFReader"
# App icon (generated by scripts/generate-icon.swift).
if [ -f "Sources/PDFReader/Resources/AppIcon.icns" ]; then
    cp "Sources/PDFReader/Resources/AppIcon.icns" "$APP_DIR/Contents/Resources/AppIcon.icns"
fi

cat > "$APP_DIR/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleExecutable</key>
	<string>PDFReader</string>
	<key>CFBundleIdentifier</key>
	<string>com.example.pdfreader</string>
	<key>CFBundleName</key>
	<string>PDFReader</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>LSMinimumSystemVersion</key>
	<string>14.0</string>
	<key>CFBundleIconFile</key>
	<string>AppIcon</string>
	<key>CFBundleIconName</key>
	<string>AppIcon</string>
</dict>
</plist>
PLIST

codesign --force --deep --sign - "$APP_DIR"
echo "Built $APP_DIR"
